# Generated by Django 2.2.3 on 2019-07-26 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coworking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='imagens/coworking_logo')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('PAGAMENTO_PENDENTE', 'Pagamento Pendente'), ('DESATIVADO', 'Desativado')], max_length=150)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='enderecos.Endereco')),
            ],
            options={
                'verbose_name': 'Coworking',
                'verbose_name_plural': "Coworking's",
            },
        ),
    ]
