# Generated by Django 2.2.3 on 2019-07-27 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190726_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworking',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endereco', to='clientes.Cliente'),
        ),
    ]
