# Generated by Django 2.2.3 on 2019-07-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_fotossala'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotossala',
            options={'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos de Salas'},
        ),
    ]
