# Generated by Django 2.2.3 on 2019-07-26 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('salas', '0003_auto_20190726_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='coworking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Coworking'),
        ),
    ]
