# Generated by Django 2.2.3 on 2019-07-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0005_auto_20190726_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='preco',
        ),
    ]
