# Generated by Django 2.2.3 on 2019-07-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0007_auto_20190727_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotossala',
            old_name='url',
            new_name='image',
        ),
    ]
