# Generated by Django 2.2.3 on 2019-08-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0008_auto_20190727_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotossala',
            name='image',
            field=models.ImageField(upload_to='imagens/salas'),
        ),
    ]
