# Generated by Django 2.2.3 on 2019-07-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('CONFIRMADO', 'Confirmado'), ('SOLICITAR_CANCELAMENTO', 'Cancelamento Solicitado'), ('CANCELADO', 'Cancelado')], max_length=150),
        ),
    ]
