# Generated by Django 2.2.3 on 2019-07-27 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_auto_20190727_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
        ),
    ]
