# Generated by Django 2.2.3 on 2019-07-27 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_auto_20190727_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('CONFIRMADO', 'Confirmado'), ('SOLICITAR_CANCELAMENTO', 'Cancelamento Solicitado'), ('CANCELADO', 'Cancelado')], max_length=150)),
                ('mensagem', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='agendamentos.Status'),
        ),
    ]
