# Generated by Django 2.2.3 on 2019-08-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_auto_20190727_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('CONFIRMADO', 'Confirmado'), ('SOLICITAR_CANCELAMENTO', 'Cancelamento Solicitado'), ('CANCELADO', 'Cancelado')], max_length=45),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
