# Generated by Django 2.2.3 on 2019-08-06 01:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0010_auto_20190805_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='horario_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario_termino',
            field=models.DateTimeField(),
        ),
    ]
