# Generated by Django 2.2.3 on 2019-07-26 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salas', '0006_remove_sala_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('periodo', models.CharField(choices=[('HORA', '1 Hora'), ('DIA', '1 Dia'), ('SEMANA', '1 Semana'), ('QUINZENA', '1 Quinzena'), ('MES', '1 Mês'), ('TRIMESTRE', '3 Mêses - Trimestre'), ('SEMESTRE', '6 Mêses - Semestre'), ('SEMESTRE', '1 Ano')], max_length=150)),
                ('sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salas.Sala')),
            ],
        ),
    ]
