# Generated by Django 2.2.3 on 2019-07-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='periodo',
            field=models.CharField(choices=[('HORA', '1 Hora'), ('4_HORAS', '4 Horas'), ('DIA_8H', '1 Diária (8 Horas)'), ('DIA_12H', '1 Diária (12 Horas)'), ('DIA_24H', '1 Diária (24 Horas)'), ('SEMANA', '1 Semana'), ('QUINZENA', '1 Quinzena'), ('MES', '1 Mês'), ('TRIMESTRE', 'Trimestre - 3 Meses'), ('SEMESTRE', 'Semestre - 6 Meses'), ('SEMESTRE', '1 Ano')], max_length=150),
        ),
    ]
