# Generated by Django 2.2.3 on 2019-07-26 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=45)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='usuarios.Usuario')),
            ],
        ),
    ]
