# Generated by Django 2.2.3 on 2019-07-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0004_endereco_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
